using System.Diagnostics;
using System.Globalization;
using System.Numerics;
using Overload.Content;
using Overload.Domain;

namespace Overload.Tools;
public static class BalanceReports
{
    public static void Export(BalanceProfile basis, string output)
    {
        Directory.CreateDirectory(output);
        Write("xp.csv", "level,total_xp,xp_to_next,resonance,skill_budget,talent_budget",
            new BigInteger[] { 1,15,40,59,60,61,99,100,101,999,1000,1001,1000001,BigInteger.Pow(10,30) }.Select(level =>
            {
                var s = FoundationRules.AddXp(new CharacterState { TotalXp = 0, ValidatedLevel = 1 }, Progression.TotalXp(level));
                return Row(level,s.TotalXp,Progression.Cost(level),Progression.Resonance(level),FoundationRules.SkillBudget(s),FoundationRules.TalentBudget(s));
            }));
        var tiers = Enumerable.Range(1,20).Select(t => new BigInteger(t)).Concat([100,1000,BigInteger.Pow(10,30)]).ToArray();
        Write("tiers.csv", "tier,reference_level,xp_budget,each_group_xp,completion_xp,gold,alloy,enemy_factor_numerator,enemy_factor_denominator,player_damage_subunits,player_life_subunits,boss_life_subunits,boss_damage_subunits",
            tiers.Select(t =>
            {
                var s = Reference(t, t); var profile = FoundationRules.Build(basis,s); var p = new PlayerCombat(profile,character:s,tier:t);
                var e = new EnemyCombat(profile.Enemies.Single(e => e.Role == EnemyRole.Bellkeeper),t); var xp=EndlessRules.ExpeditionXp(t);
                return Row(t,Progression.ReferenceLevel(t),xp,xp/10,xp-6*(xp/10),200*t,100*t,(t+24)*(t+24),625,p.AttackBudget(profile.Skills[0]),p.MaximumLife,e.MaximumLife,e.Damage);
            }));
        Write("forge.csv","from_grade,to_grade,gold,alloy,completion_gold,completion_alloy",
            tiers.Where(t => t>1).Select(t => { var q=EndlessRules.Quote(t-1,t); return Row(t-1,t,q.Gold,q.Alloy,200*t,100*t); }));
        Write("encounter-sweep.csv","tier,scenario,enemy,player_level,grade,kill_seconds,damage_taken,life_remaining,flasks_used,result",
            tiers.Take(22).SelectMany(t => new[] {"matched","entry-grade","undergeared","overleveled"}.SelectMany(scenario => basis.Enemies.Select(enemy => Simulate(basis,t,scenario,enemy)))));
        Write("benchmarks.csv","decimal_digits,iterations,xp_inverse_ms,combat_and_forge_ms,save_roundtrip_ms,allocated_bytes",
            new[] {20,60,120,300}.Select(Benchmark));
        File.WriteAllText(Path.Combine(output,"README.md"), "# E05 model reports\n\nGenerated by Overload.Tools balance-report using the runtime Progression, EndlessRules, FoundationRules, PlayerCombat and EnemyCombat classes. All growing amounts are exact decimal integers; combat amounts use 1,000 subunits.\n\nThe encounter sweep is a reproducible stationary trading model at 60 Hz, without critical hits, geometric dodging or Overload memories: prioritise flask below 60% Life, then Lance, Pulse, Cleave; land accepted attacks at their active phase, and receive every telegraphed enemy attack. Enemy windup/recovery and player Focus/cooldowns/healing run on their normal clocks. A failure is a model death or 180-second limit, not a prediction of human performance. Matched uses Q(T), G=T; entry uses G=max(1,T-1); undergeared uses G=1; overleveled uses Q(T)+40 with G=T. All use the same six starter items.\n\nNo auto-scaling to player level occurs. Repeated checkpoint supply refills, movement, equipment choice, stagger uptime, target count and player execution can change real results. Timing rows are local Stopwatch samples after warm-up, not performance guarantees. CSV export is presentation only and never feeds save values back into the game.\n");
        void Write(string name,string header,IEnumerable<string> rows) => File.WriteAllLines(Path.Combine(output,name),new[]{header}.Concat(rows));
    }
    public static CharacterState Reference(BigInteger tier, BigInteger? grade = null, int extraLevels = 0)
    {
        var level = Progression.ReferenceLevel(tier)+extraLevels;
        return FoundationRules.AddXp(new CharacterState { TotalXp=0,ValidatedLevel=1,FractureUnlocked=true,
            HighestClearedTier=tier,HighestUnlockedTier=tier+1,AttunementGrade=grade ?? tier,Chapter=EndlessRules.ChapterAt(tier+1),
            Gold=100000000,Alloy=100000000 },Progression.TotalXp(level));
    }
    private static string Simulate(BalanceProfile basis, BigInteger tier, string scenario, EnemyDefinition enemy)
    {
        var grade = scenario == "undergeared" ? BigInteger.One : scenario == "entry-grade" ? BigInteger.Max(1,tier-1) : tier;
        var s = Reference(tier,grade,scenario == "overleveled" ? 40 : 0); var profile=FoundationRules.Build(basis,s);
        var p=new PlayerCombat(profile,character:s,tier:tier); var e=new EnemyCombat(enemy,tier); p.SetCombatActive(true);
        BigInteger damageTaken=0; var ticks=0;
        var nextAttack=enemy.Windup;
        for (;ticks<10800 && !p.Dead && !e.Dead;ticks++)
        {
            p.AdvanceClock();
            if (p.Life*100 < p.MaximumLife*60) p.TryStart(SkillId.Flask,Vector2.UnitX);
            if (!p.TryStart(SkillId.ChainLance,Vector2.UnitX) && !p.TryStart(SkillId.ShieldPulse,Vector2.UnitX)) p.TryStart(SkillId.Cleave,Vector2.UnitX);
            if (p.Action is { Emitted:false } a && a.Definition.Family == ActionFamily.Assault && a.Phase(p.Tick)==ActionPhase.Active)
            { a.Emitted=true; e.ReceiveHit(p.AttackBudget(a.Definition),a.Definition.Stagger,p.Tick); }
            if (p.Tick>=nextAttack)
            {
                if (!e.Dead && p.Tick>=e.StunnedUntil) { var before=p.Life; p.ReceiveHit(e.Damage,false); damageTaken+=before-p.Life; }
                nextAttack=checked((int)p.Tick)+enemy.Windup+(e.Enraged ? Math.Max(48,enemy.Recovery*2/3) : enemy.Recovery);
            }
        }
        return Row(tier,scenario,enemy.Role,s.ValidatedLevel,grade,(ticks/60d).ToString("F3",CultureInfo.InvariantCulture),damageTaken,p.Life,profile.Hero.FlaskCharges-p.FlaskCharges,e.Dead ? "clear" : p.Dead ? "dead" : "timeout");
    }
    private static string Benchmark(int digits)
    {
        const int iterations=20; var tier=BigInteger.Pow(10,digits-1); var xp=Progression.TotalXp(Progression.ReferenceLevel(tier));
        var s=Reference(tier); s=s with { Gold=BigInteger.Pow(10,digits*3),Alloy=BigInteger.Pow(10,digits*3) };
        s=EndlessRules.Begin(s,tier,Guid.NewGuid()); var json=CharacterStore.Encode(s);
        Progression.LevelAt(xp); CharacterStore.Decode(json);
        var before=GC.GetAllocatedBytesForCurrentThread(); var watch=Stopwatch.StartNew();
        for(var i=0;i<iterations;i++) Progression.LevelAt(xp);
        var inverse=watch.Elapsed.TotalMilliseconds; watch.Restart();
        for(var i=0;i<iterations;i++) { EndlessRules.PlayerAmount(300000,tier*2,tier); EndlessRules.Quote(1,tier); EndlessRules.Mitigated(tier*tier,140,tier,tier); }
        var combat=watch.Elapsed.TotalMilliseconds; watch.Restart();
        for(var i=0;i<iterations;i++) CharacterStore.Decode(json);
        return Row(digits,iterations,inverse.ToString("F3",CultureInfo.InvariantCulture),combat.ToString("F3",CultureInfo.InvariantCulture),watch.Elapsed.TotalMilliseconds.ToString("F3",CultureInfo.InvariantCulture),GC.GetAllocatedBytesForCurrentThread()-before);
    }
    private static string Row(params object[] values) => string.Join(',',values.Select(v => Convert.ToString(v,CultureInfo.InvariantCulture)));
}
